from typing import Callable, Dict, Optional, Tuple

from .subscription import Subscription

class MqttExt:
    _mqtt: int
    _subscriptions: Dict[str, Subscription]
    _clientid: str
    _username: str
    _password: str
    _hostname: str
    _port: int
    _keepalive: int
    _broker_connected: bool = ...
    _connect_count: int = ...

    _connect_callback: Callable
    _msg_cb: Tuple[int, Callable]
    _connect_cb: Tuple[int, Callable]
    _disconnect_cb: Tuple[int, Callable]

    def __init__(
        self,
        clientid: str,
        username: Optional[str] = ...,
        password: Optional[str] = ...,
        postinitcall: Optional[Callable[[MqttExt], None]] = ...,
        hostname: str = ...,
        port: int = ...,
        keepalive: int = ...,
        connect_callback: Optional[Callable] = ...,
    ): ...
    async def __aenter__(self): ...
    async def __aexit__(self, exc_type, exc, tb): ...
    def _on_message(self, mosq: int, ctx: int, msg: int) -> None: ...
    def _on_connect(self, mosq: int, ctx: int, rc: int): ...
    def _on_disconnect(self, mosq: int, ctx: int, rc: int): ...
    def mosq_err_log(self, msg: str, mosq_rc: int): ...
    async def _incoming_loop(self): ...
    async def reconnect(self): ...
    def publish(self, topic: str, message: str, qos: int = ..., retain: bool = ...): ...
    def will_set(self, topic: str, message: str, qos: int = ..., retain: bool = ...): ...
    def subscribe(self, subscription: str, qos: int = ...) -> Subscription: ...
