#!/bin/sh /etc/rc.common
# Copyright (c) 2021 Signify Holding

# shellcheck disable=SC2034  # The variable is used by rc.common
START=80
# shellcheck disable=SC2034  # The variable is used by rc.common
STOP=80
# shellcheck disable=SC2034  # The variable is used by rc.common
USE_PROCD=1

# procd respawn settings
# RESTART_TIMEOUT = time(seconds) before next respawn
# FAIL_THRESHOLD = time(seconds) in which MAX_FAIL can be reached
# MAX_FAIL = max number of respawns within FAIL_THRESHOLD.
RESTART_TIMEOUT_OVERRIDE=$(fw_printenv -n restart_timeout_override 2>/dev/null)
RESTART_TIMEOUT=${RESTART_TIMEOUT_OVERRIDE:-40}
FAIL_THRESHOLD=3600 #standard behaviour
MAX_FAIL=25

# micropython settings
# MICROPY_HEAP_SIZE = heap size allocated by the micropython interpreter
MICROPY_HEAP_SIZE="640K"

# the limit on the total size of data pages the process is allowed to allocate
MMAP_DATA_LIMIT=2097152

DAEMON="updated"
USER="$DAEMON"
PROG="/usr/bin/$DAEMON"

if [ -n "$(fw_printenv -n product_updated_verbose 2>/dev/null)" ]; then
  VERBOSE="--verbose"
fi

check_preconditions () {
	user_exists $USER || user_add $USER
}

start_service() {
	check_preconditions

	procd_open_instance
	procd_set_param command "${PROG}" --use_syslog  ${VERBOSE}
	procd_set_param env MICROPY_HEAP_SIZE=$MICROPY_HEAP_SIZE
	procd_set_param limits mmap="${MMAP_DATA_LIMIT} ${MMAP_DATA_LIMIT}"
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param exitlog /tmp/exitlog/updated.exit
	procd_set_param respawn ${FAIL_THRESHOLD} ${RESTART_TIMEOUT} ${MAX_FAIL}
	procd_set_param fail reboot
	procd_close_instance
}
