#!/bin/sh

[ "$(uci -q get system.@system[0].hostname)" != "Philips-hue" ] && exit 0

new_name=`cat /sys/class/net/eth1/address | sed 's/://g'`

uci -q batch <<-EOF >/dev/null
        set system.@system[0].hostname=${new_name}
        commit system
EOF

exit 0
