#!/usr/bin/env ash
# shellcheck shell=dash

# Copyright (c) 2020 Signify Holding

BRIDGE_KEY_FILE=/etc/ssl/private/bridge.key.pem
BRIDGE_CERT_FILE=/etc/ssl/certs/bridge.cert.pem
OPENSSL_CONFIG=/etc/webserver/openssl.cfg

FACTORY_INSTALLED_CREDENTIALS_UBOOT_ID="cert_server_prime256v1_sha256"
SERVER_INSTALLED_CREDENTIALS_UBOOT_ID="cert_hue_prime256v1_sha256"
SELF_SIGNED_CREDENTIALS_UBOOT_ID="cert_server_self_prime256v1_sha256"

_getUBootVariable () {
    fw_printenv -n "${1}"
}

_getUBootVariableWithoutExit () {
    set +e
    fw_printenv -n "${1}"
    set -e
}

_getBridgeID () {
    _getUBootVariable eui64
}

_ubootContainsCertificate() {
    local NAME=$1
    _getUBootVariable "${NAME}"
}

_installCredentialsFromUboot() {
    local NAME=$1
    if _getUBootVariable "${NAME}"; then
        _getUBootVariable "${NAME}" | webserver-credentials-serdes decode-key > ${BRIDGE_KEY_FILE}
        _getUBootVariable "${NAME}" | webserver-credentials-serdes decode-cert > ${BRIDGE_CERT_FILE}
        chmod 400 ${BRIDGE_KEY_FILE}
    fi
}

_generateBridgeKey () {
    openssl ecparam -name prime256v1 -genkey -out ${BRIDGE_KEY_FILE}
    chmod 400 ${BRIDGE_KEY_FILE}
}

_generateSelfSignedCredentials () {
    local TEMP_CERTS_LOCATION="/tmp/newcerts"

    rm -rf "${TEMP_CERTS_LOCATION}"
    mkdir -p "${TEMP_CERTS_LOCATION}"
    cd "${TEMP_CERTS_LOCATION}" || return

    mkdir -p certs
    mkdir -p csr
    mkdir -p newcerts
    mkdir -p private
    touch index.txt

    _getBridgeID > serial

    openssl req -new -config ${OPENSSL_CONFIG} -extensions server_cert -key ${BRIDGE_KEY_FILE} -out bridge.csr -subj "/C=NL/O=Philips Hue/CN=$(_getBridgeID)"
    openssl ca -config ${OPENSSL_CONFIG} -extensions server_cert  -md sha256 -in bridge.csr -keyfile ${BRIDGE_KEY_FILE} -selfsign -startdate 20170101000000Z -enddate 20380101000000Z -notext -out ${BRIDGE_CERT_FILE}.new -batch > /dev/null

    mv ${BRIDGE_CERT_FILE}.new ${BRIDGE_CERT_FILE}
    rm -rf "${TEMP_CERTS_LOCATION}"
}

_saveSelfSignedCredentialsToUboot() {
    fw_setenv ${SELF_SIGNED_CREDENTIALS_UBOOT_ID} "$(cat ${BRIDGE_KEY_FILE} ${BRIDGE_CERT_FILE} | webserver-credentials-serdes encode)"
}

if [ -n "$(_getUBootVariableWithoutExit ${SERVER_INSTALLED_CREDENTIALS_UBOOT_ID})" ]; then
    _installCredentialsFromUboot ${SERVER_INSTALLED_CREDENTIALS_UBOOT_ID}
elif _ubootContainsCertificate ${FACTORY_INSTALLED_CREDENTIALS_UBOOT_ID}; then
    _installCredentialsFromUboot ${FACTORY_INSTALLED_CREDENTIALS_UBOOT_ID}
elif _ubootContainsCertificate ${SELF_SIGNED_CREDENTIALS_UBOOT_ID}; then
    _installCredentialsFromUboot ${SELF_SIGNED_CREDENTIALS_UBOOT_ID}
else
    _generateBridgeKey
    _generateSelfSignedCredentials
    _saveSelfSignedCredentialsToUboot
fi
