#!/bin/sh
# Copyright (c) 2019 Signify Holding

HOMEKIT_HUE_SRV_PATH=/home/homekit/mdns-config
HOMEKIT_HUE_INSTANCE_NAME='Philips Hue'
HOMEKIT_HUE_TYPE_NAME=_hue._tcp
HOMEKIT_HUE_PORT=80
HOMEKIT_HUE_BRIDGEID=`fw_printenv -n eui64`
HOMEKIT_HUE_MODELID=`fw_printenv -n board`

generate_configuration() {
    local HOMEKIT_HUE_INSTANCE_NAME_END=`echo $HOMEKIT_HUE_BRIDGEID | tail -c 7 | tr '/a-z/' '/A-Z/'`

    echo "instance_name=$HOMEKIT_HUE_INSTANCE_NAME - $HOMEKIT_HUE_INSTANCE_NAME_END"
    echo "type_name=$HOMEKIT_HUE_TYPE_NAME"
    echo "port=$HOMEKIT_HUE_PORT"
    echo "bridgeid=$HOMEKIT_HUE_BRIDGEID"
    echo "modelid=$HOMEKIT_HUE_MODELID"
}

configure_hue_service() {
  local CONFIG_FILE="$HOMEKIT_HUE_SRV_PATH/$HOMEKIT_HUE_TYPE_NAME"

  if [ $HOMEKIT_HUE_BRIDGEID ] && [ $HOMEKIT_HUE_MODELID ]; then
    generate_configuration > $CONFIG_FILE.new
    sync $CONFIG_FILE.new
    mv $CONFIG_FILE.new ${CONFIG_FILE}
    sync $CONFIG_FILE
  fi
}

configure_hue_service

exit 0