#!/bin/sh /etc/rc.common
# Copyright (c) 2022 Signify Holding

START=81
STOP=81
USE_PROCD=1

# Must be in line with rest of system
WATCHDOG_DETAILEDREASON_POWER_ON=17

USER=groups
USERID=1000

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1
SERVICE_PID_FILE=/var/run/groups.pid
GROUPS=/usr/bin/groups

HUE_GROUPS_RESETREASON_DIR=/var/platform/
HUE_GROUPS_RESETREASON=${HUE_GROUPS_RESETREASON_DIR}/groups-resetreason

# procd respawn settings
# RESTART_TIMEOUT = time(seconds) before next respawn
# FAIL_THRESHOLD = time(seconds) in which MAX_FAIL can be reached
# MAX_FAIL = max number of respawns within FAIL_THRESHOLD.
RESTART_TIMEOUT_OVERRIDE=$(fw_printenv -n restart_timeout_override 2>/dev/null)
RESTART_TIMEOUT=${RESTART_TIMEOUT_OVERRIDE:-40}
FAIL_THRESHOLD=3600
MAX_FAIL=25

setResetReason() {
	local REASON=$1;shift
	echo "${REASON}" > ${HUE_GROUPS_RESETREASON}
	chown $USER:$USER ${HUE_GROUPS_RESETREASON}
}

formatCmdLineArguments() {
    echo -n "${GROUPS_ARGS:+ ${GROUPS_ARGS}}"
}

check_preconditions () {
	user_exists $USER || user_add $USER $USERID
	group_exists $USER || group_add $USER $USERID && group_add_user $USER $USER
	chown -R $USER:$USER /home/groups/
	mkdir -p /tmp/clipv2_cache
	chmod 777 /tmp/clipv2_cache
	touch /tmp/clipv2_cache/clipv2_cache.lmdb
	touch /tmp/clipv2_cache/clipv2_cache.lmdb-lock
	chmod 666 /tmp/clipv2_cache/clipv2_cache.lmdb
	chmod 666 /tmp/clipv2_cache/clipv2_cache.lmdb-lock
}

start_service() {
	check_preconditions

	procd_open_instance

	setResetReason ${WATCHDOG_DETAILEDREASON_POWER_ON}

	local ARGS="`formatCmdLineArguments`"

	procd_set_param user $USER
	procd_set_param command ${GROUPS} ${ARGS}
	procd_set_param nice "-2"
	procd_set_param exitlog /tmp/exitlog/groups.exit
	procd_set_param respawn ${FAIL_THRESHOLD} ${RESTART_TIMEOUT} ${MAX_FAIL}
	procd_set_param fail reboot
	procd_close_instance
}

stop() {
	service_stop ${GROUPS}
}
