#!/bin/sh /etc/rc.common
# Philips Company Confidential.
# Copyright (C) 2018 Signify
# All rights reserved.

START=81
STOP=81
USE_PROCD=1

# Must be in line with rest of system
WATCHDOG_DETAILEDREASON_POWER_ON=17

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1
SERVICE_PID_FILE=/var/run/clipd.pid
CLIPD=/usr/bin/clipd
HTTP_SERVER=127.0.0.1:9003
API_SCHEMAS_DIR=/etc/clipd

# procd respawn settings
# RESTART_TIMEOUT = time(seconds) before next respawn
# FAIL_THRESHOLD = time(seconds) in which MAX_FAIL can be reached
# MAX_FAIL = max number of respawns within FAIL_THRESHOLD.
RESTART_TIMEOUT_OVERRIDE=$(fw_printenv -n restart_timeout_override 2>/dev/null)
RESTART_TIMEOUT=${RESTART_TIMEOUT_OVERRIDE:-40}
FAIL_THRESHOLD=3600
MAX_FAIL=25

case $(fw_printenv -n board 2>/dev/null) in
  bsb002) EVENT_MAX_MESSAGE_SIZE=35000;;
  *) EVENT_MAX_MESSAGE_SIZE=120000;;
esac

start_service() {
	local BRIDGE_ID=$(fw_printenv -n eui64 | tr [A-Z] [a-z])
	local IGNORE_CLIP_APP_SIGNATURE=0
	local IGNORE_CLIP_APP_SIGNATURE_VALUE=$(fw_printenv -n ignore_clip_app_signature 2>/dev/null)
	if [ `echo ${IGNORE_CLIP_APP_SIGNATURE_VALUE} | grep -we "Y"` ]; then
		IGNORE_CLIP_APP_SIGNATURE=1
	fi

	procd_open_instance

	procd_set_param command ${CLIPD} --clip_server_address ${HTTP_SERVER} --clip_api_schema ${API_SCHEMAS_DIR} --bridge_id ${BRIDGE_ID} --ignore_clip_app_signature ${IGNORE_CLIP_APP_SIGNATURE} --event_max_message_size ${EVENT_MAX_MESSAGE_SIZE}
	procd_set_param exitlog /tmp/exitlog/clipd.exit
	procd_set_param respawn ${FAIL_THRESHOLD} ${RESTART_TIMEOUT} ${MAX_FAIL}
	procd_set_param fail reboot
	procd_close_instance
}

stop() {
	service_stop ${CLIPD}
}
