#!/bin/sh

addEventingFirewallRule()
{
  uci -q get firewall.eventing && exit 1

  echo "Adding eventing firewall rule..."

uci -q batch <<-EOF >/dev/null
  set firewall.eventing=rule
  set firewall.eventing.name=Allow-Eventing
  set firewall.eventing.src=lan
  set firewall.eventing.proto=tcp
  set firewall.eventing.dest_port=
  set firewall.eventing.target=ACCEPT
  set firewall.eventing.family=ipv4
  commit firewall
EOF
}

removeEventingFirewallRule()
{
  uci -q get firewall.eventing || exit 1

  echo "Removing eventing firewall rule..."

uci -q batch <<-EOF >/dev/null
  del firewall.eventing
  commit firewall
EOF
}

if [ -f /home/.config/featurediversity/eventing ]; then
  addEventingFirewallRule
else
  removeEventingFirewallRule
fi

exit 1
