#!/bin/sh /etc/rc.common
# Copyright (c) 2019 Signify Holding

START=75
STOP=75
USE_PROCD=1

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1
SERVICE_PID_FILE=/var/run/platform-factoryreset.pid

PLATFORM_FACTORYRESET=/usr/sbin/factoryreset_daemon
PLATFORM_FACTORYRESET_VAR=/var/platform-factoryreset
PLATFORM_FACTORYRESET_PIPE=${PLATFORM_FACTORYRESET_VAR}/start
ARGS="-d $PLATFORM_FACTORYRESET_PIPE"

# procd respawn settings
# RESTART_TIMEOUT = time(seconds) before next respawn
# FAIL_THRESHOLD = time(seconds) in which MAX_FAIL can be reached
# MAX_FAIL = max number of respawns within FAIL_THRESHOLD.
RESTART_TIMEOUT_OVERRIDE=$(fw_printenv -n restart_timeout_override 2>/dev/null)
RESTART_TIMEOUT=${RESTART_TIMEOUT_OVERRIDE:-40}
FAIL_THRESHOLD=3600
MAX_FAIL=25

start_service() {
        mkdir -p ${PLATFORM_FACTORYRESET_VAR}
        procd_open_instance
        procd_set_param command ${PLATFORM_FACTORYRESET} ${ARGS}
        procd_set_param exitlog /tmp/exitlog/factoryreset.exit
        procd_set_param respawn $FAIL_THRESHOLD $RESTART_TIMEOUT $MAX_FAIL
        procd_set_param fail reboot
        procd_close_instance
}

stop() {
        service_stop ${PLATFORM_FACTORYRESET}
}
