# Signify Company Confidential.
# Copyright (C) 2023 Signify Holding.
# All rights reserved.

TIMEOUT_RECONNECT = 10
TIMEOUT_LOOP = 5

# mosq_err_t
MOSQ_ERR_CONN_PENDING = -1
MOSQ_ERR_SUCCESS = 0
MOSQ_ERR_NOMEM = 1
MOSQ_ERR_PROTOCOL = 2
MOSQ_ERR_INVAL = 3
MOSQ_ERR_NO_CONN = 4
MOSQ_ERR_CONN_REFUSED = 5
MOSQ_ERR_NOT_FOUND = 6
MOSQ_ERR_CONN_LOST = 7
MOSQ_ERR_TLS = 8
MOSQ_ERR_PAYLOAD_SIZE = 9
MOSQ_ERR_NOT_SUPPORTED = 10
MOSQ_ERR_AUTH = 11
MOSQ_ERR_ACL_DENIED = 12
MOSQ_ERR_UNKNOWN = 13
MOSQ_ERR_ERRNO = 14
MOSQ_ERR_EAI = 15
MOSQ_ERR_PROXY = 16
