#!/bin/sh /etc/rc.common
# Copyright (c) 2019 Signify Holding

START=79
STOP=79
USE_PROCD=1

# Must be in line with rest of system
WATCHDOG_DETAILEDREASON_POWER_ON=17

self="ipbridge.init"
SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1
SERVICE_PID_FILE=/var/run/ipbridge.pid
HUE_IPBRIDGE=/usr/sbin/ipbridge
HUE_IPBRIDGE_VAR=/var/hue-ipbridge
HUE_IPBRIDGE_PERSISTENT=/home/ipbridge/var
HUE_HOMEPATHPREFIX=/home

HUE_IPBRIDGE_RESETREASON_DIR=/var/platform/
HUE_IPBRIDGE_RESETREASON=${HUE_IPBRIDGE_RESETREASON_DIR}/ipbridge-resetreason

GPIO_DIR=/sys/class/gpio
HUE_IPBRIDGE_TTY=/dev/ttyZigbee
DM_CHANNEL_CONFIG_FILE=/etc/channel/channel-config

# procd respawn settings
# RESTART_TIMEOUT = time(seconds) before next respawn
# FAIL_THRESHOLD = time(seconds) in which MAX_FAIL can be reached
# MAX_FAIL = max number of respawns within FAIL_THRESHOLD.
RESTART_TIMEOUT_OVERRIDE=$(fw_printenv -n restart_timeout_override 2>/dev/null)
RESTART_TIMEOUT=${RESTART_TIMEOUT_OVERRIDE:-40}
FAIL_THRESHOLD=3600
MAX_FAIL=25

formatArg() {
	local OPTION=$1;shift
	local VALUE=$1;shift
	echo -n " ${OPTION} ${VALUE}"
}


determineZigbeeDevice() {
	ZIGBEE_DEVICE=${ZIGBEE_DEVICE:=$(fw_printenv -n zigbee_device)}
	if [ -z "${ZIGBEE_DEVICE}" ]; then
		ZIGBEE_DEVICE=${HUE_IPBRIDGE_TTY}
	fi
}


formatArgFromUbootEnvVar() {
	local OPTION=$1;shift
	local KEY=$1;shift
	local VALUE=$(fw_printenv -n ${KEY} 2>/dev/null)
	if [ -n "${VALUE}" ]; then
		echo -n " ${OPTION} ${VALUE}"
	fi
}

log() {
	echo "$*" | tee /dev/console
	logger -p daemon.notice -t ${self} "$*"
}

error() {
	echo "error: $*" >&2
	logger -p daemon.error -t ${self} "$*"
}

. /usr/share/zigbee_soc_updater_utils.sh
. /usr/share/determine_swversion.sh
. /usr/share/determine_resetreason.sh

getArgumentsFromUbootEnvironment() {
	formatArg -p ${HUE_IPBRIDGE_PERSISTENT}
	formatArg -z ${ZIGBEE_DEVICE}
	formatArg -h ${HUE_HOMEPATHPREFIX}
	if [ -n "${SWVERSION}" ]; then
		formatArg -v ${SWVERSION}
	fi
	formatArgFromUbootEnvVar -e eui64
	formatArgFromUbootEnvVar -n set12nc
	formatArgFromUbootEnvVar -c ctn
	formatArgFromUbootEnvVar -i cid
	formatArgFromUbootEnvVar -r frcnt
	formatArgFromUbootEnvVar -o open_tst_if
	formatArgFromUbootEnvVar -f fohlocking
	formatArgFromUbootEnvVar -k portal
	if [ -n "${WATCHDOG_MAX_MEM_USE}" ]; then
		formatArg -m ${WATCHDOG_MAX_MEM_USE}
	fi
}

start_service() {
	mkdir -p ${HUE_HOMEPATHPREFIX}
	mkdir -p ${HUE_IPBRIDGE_VAR}
	mkdir -p ${HUE_IPBRIDGE_PERSISTENT}
	mkdir -p ${HUE_IPBRIDGE_RESETREASON_DIR}

	determineZigbeeDevice
	determineSwVersion

	local ARGS="$(getArgumentsFromUbootEnvironment)"

	determineResetReason

	factoryresetZigBeeSocIfNecessary
	updateZigBeeSocIfNecessary

	procd_open_instance
	procd_set_param command ${HUE_IPBRIDGE} ${ARGS}
	procd_set_param nice "-2"
	procd_set_param exitlog /tmp/exitlog/ipbridge.exit
	procd_set_param respawn $FAIL_THRESHOLD $RESTART_TIMEOUT $MAX_FAIL
	procd_set_param fail reboot
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
