#!/bin/sh /etc/rc.common
# Copyright (c) 2021 Signify Holding

# shellcheck disable=SC2034  # The variable is used by rc.common
START=73
# shellcheck disable=SC2034  # The variable is used by rc.common
STOP=73
# shellcheck disable=SC2034  # The variable is used by rc.common
USE_PROCD=1

# procd respawn settings
# RESTART_TIMEOUT = time(seconds) before next respawn
# FAIL_THRESHOLD = time(seconds) in which MAX_FAIL can be reached
# MAX_FAIL = max number of respawns within FAIL_THRESHOLD.
RESTART_TIMEOUT_OVERRIDE=$(fw_printenv -n restart_timeout_override 2>/dev/null)
RESTART_TIMEOUT=${RESTART_TIMEOUT_OVERRIDE:-40}
FAIL_THRESHOLD=3600 #standard behaviour
MAX_FAIL=25

# micropython settings
# MICROPY_HEAP_SIZE = heap size allocated by the micropython interpreter
MICROPY_HEAP_SIZE="256K"

DAEMON="croupierd"
USER="$DAEMON"
PROG="/usr/bin/$DAEMON"

start_service() {
	procd_open_instance
	procd_set_param command $PROG
	procd_set_param env MICROPY_HEAP_SIZE=$MICROPY_HEAP_SIZE
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param exitlog /tmp/exitlog/croupierd.exit
	procd_set_param respawn ${FAIL_THRESHOLD} ${RESTART_TIMEOUT} ${MAX_FAIL}
	procd_set_param fail reboot
	procd_close_instance
}
