#!/bin/sh /etc/rc.common
# Copyright (c) 2021 Signify Holding

# shellcheck disable=SC2034  # These variables are used by rc.common
# shellcheck disable=SC2086  

START=82
STOP=82

USE_PROCD=1

# procd respawn settings
# RESTART_TIMEOUT = time(seconds) before next respawn
# FAIL_THRESHOLD = time(seconds) in which MAX_FAIL can be reached
# MAX_FAIL = max number of respawns within FAIL_THRESHOLD.
RESTART_TIMEOUT_OVERRIDE=$(fw_printenv -n restart_timeout_override 2>/dev/null)
RESTART_TIMEOUT=${RESTART_TIMEOUT_OVERRIDE:-40}

FAIL_THRESHOLD=3600
MAX_FAIL=25

DAEMON="provisioning"
USER="$DAEMON"
PROG="/usr/bin/$DAEMON"

readonly provisioning_dir="/etc/iot-credentials"

check_for_network_time () {
	grep -q -m 1 -E "ntpd|tlsdate" /tmp/ntpd/sync
}

wait_for_network_time () {
	while ! check_for_network_time
	do
		sleep 2
	done
}

boot() {
	start "$@" &
}

start_service() {
	wait_for_network_time

	procd_open_instance
	procd_set_param command ${PROG} "${provisioning_dir}"
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param exitlog /tmp/exitlog/${DAEMON}.exit
	procd_set_param respawn ${FAIL_THRESHOLD} ${RESTART_TIMEOUT} ${MAX_FAIL}
	procd_set_param fail reboot
	procd_close_instance
}

stop_service () {
	pgrep -f "${PROG}" | xargs kill # shell script spawns multiple processes
}