#!/bin/sh

if uci -q get firewall.eventing; then
	uci -q batch <<-EOF > /dev/null
		del firewall.eventing
		commit firewall
		EOF
fi

if uci -q get firewall.eventing_ipv6; then
	uci -q batch <<-EOF > /dev/null
		del firewall.eventing_ipv6
		commit firewall
		EOF
fi
